# Generated by Django 4.2.13 on 2024-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_item_mothers_maiden_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='citizenship',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='agency_employee_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gsis_id_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_maiden_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pag_ibig_id_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_zip_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_zip_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone_no',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gsid_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sss_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tin_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
