# Generated by Django 4.2.13 on 2024-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_citizenship_item_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='zipcode',
            new_name='permanent_zip_code',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_maiden_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='province',
        ),
        migrations.AddField(
            model_name='item',
            name='agency_employee_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
